server:
#  port: 5000 for only development env (local)
  error.include-message: always

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
    enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: kamilmmmdov2905@gmail.com
    password: ocmf dzzn some axso
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

logging:
  level:
    org.springframework.security: DEBUG