server:
  port: 8080
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres


# For testing with a local PostgreSQL database
# Uncomment and use the following line:
# url: jdbc:postgresql://localhost:5433/postgres
