server:
  port: 8080
#  ssl:
#    key-store:
#      location: ${SERVER_SSL_KEY_STORE}
#      password: ${SERVER_SSL_KEY_STORE_PASSWORD}
#      type: ${SERVER_SSL_KEY_STORE_TYPE}
#    key-alias: ${SERVER_SSL_KEY_ALIAS}
#    key-password: ${SERVER_SSL_KEY_PASSWORD}
#    trust-store:
#      location: ${SERVER_SSL_TRUST_STORE}
#      password: ${SERVER_SSL_TRUST_STORE_PASSWORD}
#      type: ${SERVER_SSL_TRUST_STORE_TYPE}

app:
  root_url: ${APP_ROOT_URL}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}

# For testing with a local PostgreSQL database , first you should open docker
# Uncomment and use the following line:
#  datasource:
#    url: jdbc:postgresql://localhost:5433/postgres
#    driverClassName: org.postgresql.Driver
#    username: postgres
#    password: postgres
