server:
  port: 5000
#  host: ${SOCKET_HOST:0.0.0.0}

app:
  root_url: http://localhost:5000

spring:
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: root
    password:
  h2:
    console:
      enabled: true

# For testing with a local PostgreSQL database , first you should open docker
# Uncomment and use the following line:
#  datasource:
#    url: jdbc:postgresql://localhost:5433/postgres
#    driverClassName: org.postgresql.Driver
#    username: postgres
#    password: postgres
