server:
  port: ${PORT}

app:
  root_url: ${RAILWAY_APP_URL}

spring:
  datasource:
    url: jdbc:postgresql://${RAILWAY_DB_HOST}:${RAILWAY_DB_PORT}/${RAILWAY_DB_NAME}
    driverClassName: org.postgresql.Driver
    username: ${RAILWAY_DB_USER}
    password: ${RAILWAY_DB_PASSWORD}


# For testing with a local PostgreSQL database , first you should open docker
# Uncomment and use the following line:
# url: jdbc:postgresql://localhost:5433/postgres
