server:
  port: 8080
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: ${KEY_STORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: my-ssl-key

app:
  root_url: ${APP_URL}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}

# For testing with a local PostgreSQL database , first you should open docker
# Uncomment and use the following line:
# url: jdbc:postgresql://localhost:5433/postgres
