name: Build and Deploy Spring Boot Project

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.5.0

      - name: Set up JDK 20
        uses: actions/setup-java@v2
        with:
          java-version: 20
          distribution: 'adopt'

      - name: Build
        run: |
          chmod +x mvnw
          ./mvnw clean install

          # View Surefire Reports
          ls -R ./main/target/surefire-reports
          
          # Run Maven with Debug Logging
          ./mvnw clean install -X

      # - name: Print Build Artifact Contents
      #   run: |
      #     ls -R ./main/target

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: mr-smithers-excellent/docker-build-push@v4
        name: Build & push Docker image
        with:
          image: kamil571/e-commerce_spring_boot_app
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
