name: Build and Deploy Spring Boot Project

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.5.0

      - name: Set up JDK 20
        uses: actions/setup-java@v2
        with:
          java-version: 20
          distribution: 'adopt'

      - name: Build
        run: |
          chmod +x mvnw
          ./mvnw clean install

      - name: Get Commit ID
        id: commit_id
        run: echo "::set-output name=commit_id::$(git rev-parse --short HEAD)"

      - name: Build & Push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            docker.io/kamil571/e-commerce_spring_boot_app:latest
            docker.io/kamil571/e-commerce_spring_boot_app:${{ steps.commit_id.outputs.commit_id }}